name: ncrpo_mobile_app_information

description: "A new Flutter project."

publish_to: 'none' #Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoNCRPO.png" # Replace with the path to your icon image

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/bg.png
     - assets/images/logoPNP.png
     - assets/images/logoNCRPO.png
     - assets/images/logoBP.png
     - assets/images/header.png
     - assets/images/blue.png
     - assets/images/splash.png
     - assets/images/edppas.png
     - assets/images/egov.png
