name: ncrpo_mobile_app_information

description: "A Mobile Application for NCRPO."

publish_to: 'none' #Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/icon/app_icon.png"
  flutter_lints: ^4.0.0
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
     - assets/images/bg.png
     - assets/images/logoPNP.png
     - assets/images/logoNCRPO.png
     - assets/images/logoBP.png
     - assets/images/header.png
     - assets/images/blue.png
     - assets/images/splash.png
     - assets/images/edppas.png
     - assets/images/egov.png
     - assets/images/rdNCRPO.png
     - assets/images/92.png
     - assets/images/infoText.png
     - assets/icon/app_icon.png